version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: local-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all"]

volumes:
  mongo-data:
